// Code generated by "stringer -type FieldType"; DO NOT EDIT.

package plencdesc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTypeInt-0]
	_ = x[FieldTypeUint-1]
	_ = x[FieldTypeFloat32-2]
	_ = x[FieldTypeFloat64-3]
	_ = x[FieldTypeString-4]
	_ = x[FieldTypeSlice-5]
	_ = x[FieldTypeStruct-6]
}

const _FieldType_name = "FieldTypeIntFieldTypeUintFieldTypeFloat32FieldTypeFloat64FieldTypeStringFieldTypeSliceFieldTypeStruct"

var _FieldType_index = [...]uint8{0, 12, 25, 41, 57, 72, 86, 101}

func (i FieldType) String() string {
	if i < 0 || i >= FieldType(len(_FieldType_index)-1) {
		return "FieldType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldType_name[_FieldType_index[i]:_FieldType_index[i+1]]
}
