// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comp.proto

package φλenc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trial struct {
	F1                   int32     `protobuf:"varint,1,opt,name=f1,proto3" json:"f1,omitempty"`
	F2                   []int32   `protobuf:"varint,2,rep,packed,name=f2,proto3" json:"f2,omitempty"`
	F3                   float32   `protobuf:"fixed32,3,opt,name=f3,proto3" json:"f3,omitempty"`
	F4                   []float32 `protobuf:"fixed32,4,rep,packed,name=f4,proto3" json:"f4,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Trial) Reset()         { *m = Trial{} }
func (m *Trial) String() string { return proto.CompactTextString(m) }
func (*Trial) ProtoMessage()    {}
func (*Trial) Descriptor() ([]byte, []int) {
	return fileDescriptor_eba1c69cbffee541, []int{0}
}

func (m *Trial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trial.Unmarshal(m, b)
}
func (m *Trial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trial.Marshal(b, m, deterministic)
}
func (m *Trial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trial.Merge(m, src)
}
func (m *Trial) XXX_Size() int {
	return xxx_messageInfo_Trial.Size(m)
}
func (m *Trial) XXX_DiscardUnknown() {
	xxx_messageInfo_Trial.DiscardUnknown(m)
}

var xxx_messageInfo_Trial proto.InternalMessageInfo

func (m *Trial) GetF1() int32 {
	if m != nil {
		return m.F1
	}
	return 0
}

func (m *Trial) GetF2() []int32 {
	if m != nil {
		return m.F2
	}
	return nil
}

func (m *Trial) GetF3() float32 {
	if m != nil {
		return m.F3
	}
	return 0
}

func (m *Trial) GetF4() []float32 {
	if m != nil {
		return m.F4
	}
	return nil
}

func init() {
	proto.RegisterType((*Trial)(nil), "φλenc.Trial")
}

func init() { proto.RegisterFile("comp.proto", fileDescriptor_eba1c69cbffee541) }

var fileDescriptor_eba1c69cbffee541 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0xcf, 0x2d,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0xc8, 0xc8, 0xcc, 0x49, 0xcd, 0x4b, 0x56,
	0x72, 0xe7, 0x62, 0x0d, 0x29, 0xca, 0x4c, 0xcc, 0x11, 0xe2, 0xe3, 0x62, 0x4a, 0x33, 0x94, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0x4a, 0x33, 0x04, 0xf3, 0x8d, 0x24, 0x98, 0x14, 0x98, 0xc1,
	0x7c, 0x23, 0x30, 0xdf, 0x58, 0x82, 0x59, 0x81, 0x51, 0x83, 0x29, 0x88, 0x29, 0xcd, 0x18, 0xcc,
	0x37, 0x91, 0x60, 0x51, 0x60, 0x06, 0xf3, 0x4d, 0x92, 0xd8, 0xc0, 0x06, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x67, 0x85, 0xff, 0x66, 0x00, 0x00, 0x00,
}
