// package plenc provides an efficient serialisation protocol based on protobuf, but without requiring .proto files or awkward autogenerated structs. Your structs are the basis for the serialisation.
//
// plenc makes extensive use of code generation. In normal use you don't call any of the functions in this package, Instead you use plencgen to generate serialisation and deserialisation functions for your structs that you call directly. The methods are as follows.
//
// ΦλSize returns the encoded size of the struct.
//
// ΦλAppend encodes the struct into a byte slice.
//
// ΦλUnmarshal populates the struct from encoded data.
package plenc
