// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/philpearl/plenc/prototest/test.proto

package prototest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg1 struct {
	V1                   int64    `protobuf:"zigzag64,1,opt,name=v1,proto3" json:"v1,omitempty"`
	V2                   string   `protobuf:"bytes,2,opt,name=v2,proto3" json:"v2,omitempty"`
	V3                   string   `protobuf:"bytes,3,opt,name=v3,proto3" json:"v3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg1) Reset()         { *m = Msg1{} }
func (m *Msg1) String() string { return proto.CompactTextString(m) }
func (*Msg1) ProtoMessage()    {}
func (*Msg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaac78d51eb62dd5, []int{0}
}

func (m *Msg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg1.Unmarshal(m, b)
}
func (m *Msg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg1.Marshal(b, m, deterministic)
}
func (m *Msg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg1.Merge(m, src)
}
func (m *Msg1) XXX_Size() int {
	return xxx_messageInfo_Msg1.Size(m)
}
func (m *Msg1) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg1.DiscardUnknown(m)
}

var xxx_messageInfo_Msg1 proto.InternalMessageInfo

func (m *Msg1) GetV1() int64 {
	if m != nil {
		return m.V1
	}
	return 0
}

func (m *Msg1) GetV2() string {
	if m != nil {
		return m.V2
	}
	return ""
}

func (m *Msg1) GetV3() string {
	if m != nil {
		return m.V3
	}
	return ""
}

type Msg2 struct {
	V1                   []*Msg1   `protobuf:"bytes,1,rep,name=v1,proto3" json:"v1,omitempty"`
	V2                   []uint64  `protobuf:"varint,2,rep,packed,name=v2,proto3" json:"v2,omitempty"`
	V3                   []string  `protobuf:"bytes,3,rep,name=v3,proto3" json:"v3,omitempty"`
	V4                   []float32 `protobuf:"fixed32,4,rep,packed,name=v4,proto3" json:"v4,omitempty"`
	V5                   []float64 `protobuf:"fixed64,5,rep,packed,name=v5,proto3" json:"v5,omitempty"`
	V6                   []uint32  `protobuf:"varint,6,rep,packed,name=v6,proto3" json:"v6,omitempty"`
	V7                   []int32   `protobuf:"zigzag32,7,rep,packed,name=v7,proto3" json:"v7,omitempty"`
	V8                   []byte    `protobuf:"bytes,8,opt,name=v8,proto3" json:"v8,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Msg2) Reset()         { *m = Msg2{} }
func (m *Msg2) String() string { return proto.CompactTextString(m) }
func (*Msg2) ProtoMessage()    {}
func (*Msg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaac78d51eb62dd5, []int{1}
}

func (m *Msg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg2.Unmarshal(m, b)
}
func (m *Msg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg2.Marshal(b, m, deterministic)
}
func (m *Msg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg2.Merge(m, src)
}
func (m *Msg2) XXX_Size() int {
	return xxx_messageInfo_Msg2.Size(m)
}
func (m *Msg2) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg2.DiscardUnknown(m)
}

var xxx_messageInfo_Msg2 proto.InternalMessageInfo

func (m *Msg2) GetV1() []*Msg1 {
	if m != nil {
		return m.V1
	}
	return nil
}

func (m *Msg2) GetV2() []uint64 {
	if m != nil {
		return m.V2
	}
	return nil
}

func (m *Msg2) GetV3() []string {
	if m != nil {
		return m.V3
	}
	return nil
}

func (m *Msg2) GetV4() []float32 {
	if m != nil {
		return m.V4
	}
	return nil
}

func (m *Msg2) GetV5() []float64 {
	if m != nil {
		return m.V5
	}
	return nil
}

func (m *Msg2) GetV6() []uint32 {
	if m != nil {
		return m.V6
	}
	return nil
}

func (m *Msg2) GetV7() []int32 {
	if m != nil {
		return m.V7
	}
	return nil
}

func (m *Msg2) GetV8() []byte {
	if m != nil {
		return m.V8
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg1)(nil), "plenc.prototest.Msg1")
	proto.RegisterType((*Msg2)(nil), "plenc.prototest.Msg2")
}

func init() {
	proto.RegisterFile("github.com/philpearl/plenc/prototest/test.proto", fileDescriptor_eaac78d51eb62dd5)
}

var fileDescriptor_eaac78d51eb62dd5 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd0, 0xbd, 0x6a, 0xc3, 0x30,
	0x10, 0xc0, 0x71, 0x74, 0xe7, 0xa6, 0x8d, 0xfb, 0x45, 0x0d, 0x85, 0x1b, 0x45, 0x68, 0xe1, 0x26,
	0x09, 0xdb, 0x89, 0x93, 0xb9, 0x7b, 0x17, 0x8d, 0xdd, 0x9a, 0x60, 0x92, 0x80, 0x5b, 0x8b, 0x44,
	0xbd, 0xb7, 0xe9, 0xbb, 0x96, 0x5c, 0x42, 0xc0, 0x9d, 0xb2, 0x08, 0xfd, 0x38, 0xee, 0x8f, 0x50,
	0xee, 0xd7, 0xdb, 0xb4, 0xf9, 0x59, 0xba, 0x55, 0xff, 0xe5, 0xe3, 0x66, 0xdb, 0xc5, 0xf6, 0x73,
	0xd7, 0xf9, 0xd8, 0xb5, 0xdf, 0x2b, 0x1f, 0x77, 0x7d, 0xea, 0x53, 0xbb, 0x4f, 0xfe, 0x70, 0x38,
	0x65, 0xf1, 0xa8, 0x33, 0x77, 0x9e, 0x4d, 0x9a, 0x3c, 0x7b, 0xdf, 0xaf, 0xcb, 0xe2, 0x21, 0x07,
	0x29, 0xc9, 0x58, 0xc3, 0x45, 0x00, 0x39, 0xba, 0x22, 0xb0, 0x86, 0xc7, 0x01, 0xa4, 0x52, 0xd7,
	0x84, 0x27, 0xd7, 0x93, 0x5f, 0xa3, 0x8b, 0x55, 0xf1, 0x7a, 0x5a, 0x44, 0xbe, 0xad, 0x9e, 0xdd,
	0xbf, 0xbc, 0x3b, 0xb4, 0x07, 0x3d, 0xe4, 0x6c, 0xd0, 0xc3, 0x63, 0x4f, 0x3d, 0xa5, 0xcc, 0x22,
	0x43, 0x00, 0x99, 0xaa, 0x67, 0x74, 0x65, 0x91, 0x4d, 0x00, 0x99, 0xa9, 0x1b, 0x1a, 0x59, 0xe4,
	0xfb, 0x00, 0xd2, 0xa8, 0xe7, 0x74, 0x6d, 0x91, 0x9f, 0x02, 0xc8, 0x5c, 0xbd, 0xa0, 0x1b, 0x6b,
	0xf8, 0x2e, 0x80, 0x2c, 0xde, 0xca, 0x7c, 0x7c, 0x7e, 0xc5, 0xc7, 0xcb, 0x25, 0xdf, 0xb4, 0x1c,
	0xe9, 0xb5, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xab, 0x4c, 0xa3, 0xc4, 0x55, 0x01, 0x00, 0x00,
}
